---
- name: Install Shorewall
  apt:
    name: "{{ shorewall_packages }}"
    state: present

- name: Create Shorewall systemd service drop-in directory
  file:
    path: /etc/systemd/system/shorewall.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

# Workaround for restart clearing Docker rules, see:
# https://shorewall.org/Docker.html#idm23
- name: Create Shorewall systemd service drop-in snippet
  copy:
    dest: /etc/systemd/system/shorewall.service.d/ansible.conf
    content: |
      # Ansible managed
      [Service]
      ExecStop=
      ExecStop=/sbin/shorewall $OPTIONS stop
    mode: 0644
  notify: reload systemd

- name: Divert Shorewall configuration files
  command: >
    dpkg-divert --quiet --local
    --divert {{ item }}.dpkg-divert
    --rename {{ item }}
  args:
    creates: "{{ item }}.dpkg-divert"
  with_items:
    - /etc/default/shorewall
    - /etc/shorewall/shorewall.conf
    - /etc/shorewall/params

- name: Install Shorewall configuration files
  template:
    src: "{{ item.src | d(item) }}.j2"
    dest: "/{{ item.src | d(item) }}"
    owner: "{{ item.owner | d(omit) }}"
    group: "{{ item.group | d(omit) }}"
    mode: "{{ item.mode | d(omit) }}"
  loop:
    - etc/default/shorewall
    - etc/shorewall/shorewall.conf
    - etc/shorewall/hosts
    - etc/shorewall/interfaces
    - src: etc/shorewall/params
      mode: "0640"
    - etc/shorewall/policy
    - etc/shorewall/routes
    - etc/shorewall/rules
    - etc/shorewall/snat
    - etc/shorewall/start
    - etc/shorewall/tunnels
    - etc/shorewall/zones
  notify:
    - check shorewall
    - restart shorewall

- name: Enable and start Shorewall
  service:
    name: shorewall
    enabled: "{{ shorewall_service_enabled }}"
    state: "{{ shorewall_service_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
