---
- name: Reload systemd
  listen: reload systemd
  systemd:
    daemon_reload: yes
  when: ansible_service_mgr == "systemd"

- name: Check and restart Shorewall
  listen: check and restart shorewall
  command: shorewall check
  notify: restart shorewall
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart Shorewall
  listen: restart shorewall
  service:
    name: shorewall
    state: "{{ shorewall_restart_handler_state }}"
  when: shorewall_service_state == "started"
  ignore_errors: "{{ ansible_check_mode }}"
