---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure Shorewall is installed
      stat:
        path: "/usr/sbin/shorewall"
      register: result
      changed_when: false
      failed_when: result.stat.isreg is not defined or not result.stat.isreg
    - name: Ensure permissions on params configuration file are correct
      stat:
        path: "/etc/shorewall/params"
      register: shorewall_params
      failed_when: shorewall_params.stat.mode != "0640"
    - name: Ensure rule from shorewall_group_rules is present
      command:
        argv:
          - grep
          - -q
          - ^HTTPS(ACCEPT) net $FW
          - /etc/shorewall/rules
      changed_when: false
    - name: Ensure rule from shorewall_host_rules is present
      command:
        argv:
          - grep
          - -q
          - ^IMAP(ACCEPT) net $FW
          - /etc/shorewall/rules
      changed_when: false
    - name: Ensure Docker support is enabled
      command:
        argv:
          - grep
          - -q
          - ^DOCKER=Yes
          - /etc/shorewall/shorewall.conf
      changed_when: false
    - name: Ensure dynamic blacklist support is set correctly
      command:
        argv:
          - grep
          - -q
          - ^DYNAMIC_BLACKLIST=ipset-only,disconnect
          - /etc/shorewall/shorewall.conf
      changed_when: false
