---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure Shorewall is installed
      stat:
        path: "/usr/sbin/shorewall"
      register: result
      changed_when: false
      failed_when: result.stat.isreg is not defined or not result.stat.isreg
